spring:
  data:
    cassandra:
      contact-points: localhost
      port: 9042
      username: cassandra
      password: cassandra
      keyspace-name: tacocloud
      schema-action: CREATE_IF_NOT_EXISTS
      local-datacenter: datacenter1
