spring:
  data:
    rest:
      base-path: /api
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    generate-unique-name: false
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taco_cloud?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
#    template:
#      exchange: tacocloud.orders
#      routing-key: kitchens.central
  #  ldap:
  #    embedded:
  #      ldif: classpath:users.ldif
  #      base-dn: ou=groups,dc=tacocloud,dc=com
  #      port: 33389
#  activemq:
#    broker-url: tcp://127.0.0.1:61616
#    user: admin
#    password: password
#  jms:
#    template:
#      default-destination: tacocloud.order.queue