spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    generate-unique-name: false
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taco_cloud?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
#  ldap:
#    embedded:
#      ldif: classpath:users.ldif
#      base-dn: ou=groups,dc=tacocloud,dc=com
#      port: 33389
