server:
  port: 8081
spring:
  application:
    name: organizationservice # Logical name of the service that will be registered with Eureka
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://localhost:5432/eagle_eye_local'
    username: postgres
    password: '123456'
eureka:
  instance:
    prefer-ip-address: true # Register the IP of the service rather than the server name.
  client:
    register-with-eureka: true # Register the service with Eureka.
    fetch-registry: true # Pull down a local copy of the registry.
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Location of the Eureka Service
