server:
  port: 8761 # Port Eureka Server is going to listen on

eureka:
  client:
    register-with-eureka: false # Port Eureka Server is going to listen on
    fetch-registry: false # Don't cache registry information locally.
  server:
    wait-time-in-ms-when-sync-empty: 5 # Initial time to wait before server takes requests